version: "3.6"

networks:
  default:
    name: wpf_network
    driver: overlay
  lb-common:
    external: true

services:
  whospeaksfirst:
    image: ${REGISTRY}/whospeaksfirst
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.backend=whospeaksfirst"
        - "traefik.docker.network=lb-common"
        - "traefik.port=8000"
        - "traefik.frontend.entryPoints=http"
        - "traefik.enable=true"
        ## Bug fix / https://github.com/containous/traefik/issues/563#issuecomment-421360934
        - "traefik.frontend.redirect.regex=^(.*)/whospeaksfirst$$"
        - "traefik.frontend.redirect.replacement=$$1/whospeaksfirst/"
        - "traefik.frontend.rule=Host:${SERVER_HOST};PathPrefix:/whospeaksfirst;ReplacePathRegex: ^/whospeaksfirst/(.*) /$$1"
    networks:
      - default
      - lb-common
